# Generated by Django 5.2.12 on 2026-04-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_auto_20260402_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
